#!/usr/bin/env python3
"""
Figure 3: Station-level relative error |Δτ_w|/|τ_w| vs cancellation parameter ε.

Regenerated from wall-profile data + ODE evaluation.
"""

import sys, os
import numpy as np
from scipy.optimize import brentq

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'utils'))
from data_paths import get_uwf_results_dir
from plotting_utils import setup_style, save_figure
import matplotlib.pyplot as plt

setup_style(font_size=9, use_tex=True)
UWF_DIR = str(get_uwf_results_dir())
NEW_DIR = os.path.join(os.path.dirname(__file__), '..', 'new_data_download')
RESULTS_DIR = os.path.join(os.path.dirname(__file__), '..', 'results')
FIG_DIR = os.path.join(os.path.dirname(__file__), '..', '..', 'manuscript', 'figures')

# ── ODE solver (same as ode_wall_model.py) ────────────────────────
KAPPA, A_PLUS, N_GRID = 0.41, 26.0, 500

def solve_ode_for_U(tau_w, y_match, dp_dx, nu, n_grid=N_GRID):
    u_tau = np.sqrt(max(abs(tau_w), 1e-30))
    eta = np.linspace(0, 1, n_grid)
    y = y_match * eta ** 1.5
    y_plus = y * u_tau / nu
    D = 1.0 - np.exp(-y_plus / A_PLUS)
    l_m = KAPPA * y * D
    l_m2 = l_m * l_m
    F = tau_w + dp_dx * y
    absF, signF = np.abs(F), np.sign(F)
    disc = nu ** 2 + 4.0 * l_m2 * absF
    viscous = l_m2 < 1e-30
    l_m2_safe = np.where(viscous, 1.0, l_m2)
    absS = (-nu + np.sqrt(disc)) / (2.0 * l_m2_safe)
    absS = np.where(viscous, absF / nu, absS)
    S = signF * absS
    dy = np.diff(y)
    return np.sum(0.5 * (S[:-1] + S[1:]) * dy)

def predict_tau_w(U_match, y_match, dp_dx, nu):
    if abs(U_match) < 1e-15 and abs(dp_dx) < 1e-15:
        return 0.0
    def residual(tw):
        return solve_ode_for_U(tw, y_match, dp_dx, nu) - U_match
    visc_est = abs(nu * U_match / y_match) if y_match > 0 else 1e-6
    dp_est = abs(dp_dx * y_match)
    scale = max(visc_est, dp_est, 1e-8) * 5.0
    lo, hi = -scale, scale
    try:
        f_lo, f_hi = residual(lo), residual(hi)
    except Exception:
        return np.nan
    for _ in range(12):
        if f_lo * f_hi < 0:
            break
        lo *= 3.0; hi *= 3.0
        try:
            f_lo, f_hi = residual(lo), residual(hi)
        except Exception:
            return np.nan
    if f_lo * f_hi >= 0:
        taus = np.linspace(lo, hi, 30)
        fs = np.array([residual(t) for t in taus])
        sc = np.where(np.diff(np.sign(fs)))[0]
        if len(sc) > 0:
            lo, hi = taus[sc[0]], taus[sc[0] + 1]
        else:
            return np.nan
    try:
        return brentq(residual, lo, hi, xtol=1e-12, rtol=1e-8, maxiter=100)
    except Exception:
        return np.nan

Y_IDX = 10

# ── Datasets to plot ──────────────────────────────────────────────

datasets = [
    # (file, label, marker, color)
    (os.path.join(UWF_DIR, 'separation_bubble_caseC_wall_profiles.npz'),
     'Sep. bubble', 'X', '#BCBD22'),
    (os.path.join(UWF_DIR, 'nasa_hump_Re936000_wall_profiles.npz'),
     'NASA hump', 'o', '#F58518'),
    (os.path.join(UWF_DIR, 'bfs_Re13700_wall_profiles.npz'),
     'BFS', 'P', '#17BECF'),
    # Hill-surface-aware extraction (eq:hillsurface): the legacy y=0-pinned
    # file samples velocity inside the solid hill on the hill faces, giving a
    # spurious near-zero tau_w (tiny eps, blown-up relative error). The
    # corrected per-station profiles are regenerated by
    # analysis/build_corrected_pehill_profiles.py from the same raw DNS.
    (os.path.join(RESULTS_DIR, 'periodic_hills_case_1p0_wall_profiles_corrected.npz'),
     'Periodic hills', 'p', '#D62728'),
    # New datasets
    (os.path.join(NEW_DIR, 'jaxa_sep_bubble_Re600_wall_profiles.npz'),
     'JAXA sep. bubble', '+', '#7F7F7F'),
    (os.path.join(NEW_DIR, 'swept_separation_caseC35_wall_profiles.npz'),
     'Swept sep.', 'd', '#E377C2'),
    (os.path.join(NEW_DIR, 'conv_div_channel_Re12600_wall_profiles.npz'),
     'Conv-div ch.', 's', '#8C564B'),
    (os.path.join(NEW_DIR, 'gaussian_bump_Re2M_wall_profiles.npz'),
     'Gauss. bump', '^', '#9467BD'),
]

# ── Evaluate and collect per-station data ─────────────────────────

all_eps = []
all_rel_err = []
all_labels = []
all_markers = []
all_colors = []

for filepath, label, marker, color in datasets:
    if not os.path.isfile(filepath):
        print(f"  Skipping {label}: file not found")
        continue

    d = np.load(filepath, allow_pickle=True)
    y = d['y']
    U = d['U']
    tau_w_dns = d['tau_w'].ravel()
    dp_dx = d['dp_dx'].ravel()
    nu_arr = d['nu'].ravel()
    n = len(tau_w_dns)

    for i in range(n):
        yi = y[i] if y.ndim == 2 else y
        Ui = U[i] if U.ndim == 2 else U
        if Y_IDX >= len(yi):
            continue
        y_m, U_m = yi[Y_IDX], Ui[Y_IDX]
        if y_m <= 0 or np.isnan(U_m):
            continue

        # Epsilon
        denom = abs(dp_dx[i]) * y_m
        if denom < 1e-30 or abs(tau_w_dns[i]) < 1e-30:
            continue
        eps = abs(tau_w_dns[i]) / denom

        # ODE prediction
        tw_pred = predict_tau_w(U_m, y_m, float(dp_dx[i]), float(nu_arr[i]))
        if np.isnan(tw_pred):
            continue

        rel_err = abs(tw_pred - tau_w_dns[i]) / abs(tau_w_dns[i])

        all_eps.append(eps)
        all_rel_err.append(rel_err)
        all_labels.append(label)
        all_markers.append(marker)
        all_colors.append(color)

    print(f"  {label}: done")

all_eps = np.array(all_eps)
all_rel_err = np.array(all_rel_err)

print(f"\nTotal stations: {len(all_eps)}")

# ── log-log correlation and best-fit slope of error vs 1/eps ──────
_lm = (all_eps > 0) & (all_rel_err > 0) & np.isfinite(all_eps) & np.isfinite(all_rel_err)
_x = np.log10(1.0 / all_eps[_lm])
_y = np.log10(all_rel_err[_lm])
_r = float(np.corrcoef(_x, _y)[0, 1])
_slope = float(np.polyfit(_x, _y, 1)[0])
_ph = np.array([l == 'Periodic hills' for l in all_labels])[_lm]
print(f"log-log correlation r(error, 1/eps) = {_r:.3f}; best-fit slope = {_slope:.3f}")
if _ph.any():
    print(f"periodic-hills stations: eps in "
          f"[{all_eps[np.array([l=='Periodic hills' for l in all_labels])].min():.3f}, "
          f"{all_eps[np.array([l=='Periodic hills' for l in all_labels])].max():.3f}], "
          f"rel.err in "
          f"[{all_rel_err[np.array([l=='Periodic hills' for l in all_labels])].min():.2f}, "
          f"{all_rel_err[np.array([l=='Periodic hills' for l in all_labels])].max():.2f}]")
np.savez(os.path.join(RESULTS_DIR, 'error_vs_epsilon_data.npz'),
         eps=all_eps, rel_err=all_rel_err,
         labels=np.array(all_labels), loglog_r=_r, slope=_slope,
         n_stations=len(all_eps))

# ── Figure ────────────────────────────────────────────────────────

fig, ax = plt.subplots(1, 1, figsize=(5.5, 4.0))

# Shaded zones
ax.axvspan(1e-6, 1.0, alpha=0.06, color='#d62728', zorder=0)
ax.axvspan(1.0, 1e8, alpha=0.04, color='#2ca02c', zorder=0)

# Plot by label group
plotted = set()
for label in dict.fromkeys(all_labels):  # preserve order, unique
    mask = np.array([l == label for l in all_labels])
    marker = all_markers[np.argmax(mask)]
    color = all_colors[np.argmax(mask)]
    show_label = label not in plotted
    plotted.add(label)

    ax.scatter(all_eps[mask], all_rel_err[mask],
               marker=marker, c=color, s=20, alpha=0.6,
               edgecolors='0.3', linewidths=0.2, zorder=4,
               label=label if show_label else None)

# O(1/ε) reference line
eps_line = np.logspace(-5, 7, 100)
ax.plot(eps_line, 1.0 / eps_line, '--', color='0.4', lw=1.0, alpha=0.6,
        label=r'$O(1/\varepsilon)$', zorder=3)

# Annotations — moved DOWN to ~10^-4 to avoid covering data
ax.text(3e-3, 1.5e-4, r'$\varepsilon \ll 1$' + '\n' + r'\textbf{ODE fails}',
        fontsize=7, ha='center', color='#b00000',
        bbox=dict(boxstyle='round,pad=0.2', fc='white', ec='#b00000', alpha=0.9),
        zorder=10)

ax.text(3e3, 1.5e-4, r'$\varepsilon \gg 1$' + '\n' + r'\textbf{ODE works}',
        fontsize=7, ha='center', color='#2E7D32',
        bbox=dict(boxstyle='round,pad=0.2', fc='white', ec='#2E7D32', alpha=0.9),
        zorder=10)

ax.set_xscale('log')
ax.set_yscale('log')
ax.set_xlabel(r'$\varepsilon = |\tau_w|/(|\mathrm{d}p/\mathrm{d}x|\,y_m)$')
ax.set_ylabel(r'Relative error $|\Delta\tau_w|/|\tau_w|$')
ax.set_xlim(1e-5, 1e7)
ax.set_ylim(1e-5, 1e5)

ax.legend(fontsize=6.5, loc='upper right', framealpha=0.9, ncol=2)

fig.tight_layout()
save_figure(fig, 'error_vs_epsilon', fig_dir=FIG_DIR)
print(f"\nSaved to {FIG_DIR}/error_vs_epsilon.pdf")
