#!/usr/bin/env python3
"""model_matched_transfer_l2.py -- L2 instrument (development/nodes/node_010).

WHAT THIS IS
------------
The R2-3/M6 coupled matching-surface campaign (14 logical cases, terminal on
ARCHER2) is sound raw data.  Its *reduction* carried four estimand defects that
made the published comparison unfair.  This script is the replacement
measurement instrument.  It runs on the already-deposited terminal campaign; it
launches nothing and re-runs no CFD.

The four repairs, each of which changes a number that appears in the paper:

  (R1) MODEL IDENTITY.  ``harvest_r2_3_ym.py`` interpolates ONE a-priori sweep
       (``epsilon_coupled_predictor.npz``, generated by the pressure-gradient
       ODE architecture ``ode_wall_model.predict_tau_w``) and writes it into
       BOTH the equilibrium and the total-gradient-TBLE rows, byte-identically.
       Any "a-priori -> coupled transfer" statistic computed from that column
       compares coupled equilibrium against a pressure-gradient a-priori model.
       Here each coupled arm is paired with the a-priori evaluation of ITS OWN
       deployed architecture, and the pairing is *proved* by reading the
       OpenFOAM ``nut`` boundary condition out of every case:

           nutUSpaldingWallFunction  <->  M0_equilibrium  (Spalding)
           totalGradientTbleNut      <->  M1_pressure_gradient_ode

       The a-priori model is evaluated at the coupled run's own measured
       per-face matching surface (phase, y_m), i.e. the same physical surface,
       so only the model architecture differs between the two branches.

  (R2) COMMENSURATE SENSITIVITY.  The deposited averaging-window sensitivity is
       RMS(tau_270 - tau_225)/RMS(tau_270), a curve-difference norm, while the
       station and grid sensitivities are differences of E_tau.  Their ratio is
       not a dominance statement.  Here every checkpoint (windows 180/225/270)
       is scored against the same DNS truth in the same E_tau and R^2 estimands
       used for station and grid, so all three sensitivities are differences of
       one quantity.

  (R3) CASE-CORRECT CRITICAL HEIGHT.  ``YCRIT_PAPER = 15.925931`` is the
       ``krank_pehill_Re10595`` row of ``critical_matching_height_map.npz``.
       The case under test is the Xiao Re_H=5600 hill, whose own row is
       ``periodic_hills_1p0`` with y_crit+ = 1.0 -- the lower edge of the
       swept y+ grid, i.e. no interior crossing.  This script uses the
       case's own row and reports where the sampled surfaces sit relative to it.

  (R4) DRIVE-GATE PROVENANCE.  The registered admission check was "measured
       crest bulk within 3%" on a single z = 2.25 sample line.  Two points fail
       it.  This script records that outcome as FAILED, binds the corrected
       drive to the exact controller/volume identity instead, and demotes the
       slice fluxes to an ancillary spanwise-homogeneity diagnostic with no
       pass/fail authority.  No post-outcome ceiling is applied.

Outputs
-------
    codes/results/model_matched_transfer_l2_<date>.npz
    codes/results/model_matched_transfer_l2_<date>_summary.json

Exit 0 only if every internal consistency assertion holds.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import math
import re
import sys
from pathlib import Path
from typing import Any

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import harvest_m13_highre as HM          # noqa: E402
import harvest_r2_3_ym as HR             # noqa: E402
import r2m4_ladder_common as C           # noqa: E402

ROOT = HM.ROOT
SCHEMA = "model-matched-transfer-l2-v1"

# ---------------------------------------------------------------------------
# (R1) The model-identity map.  Left: the OpenFOAM nut boundary condition that
# the coupled arm actually deployed.  Right: the a-priori ladder member with
# the same architecture.  Verified per case by reading input/nut.
# ---------------------------------------------------------------------------
DEPLOYED_BC = {
    "equilibrium": "nutUSpaldingWallFunction",
    "total_gradient_tble": "totalGradientTbleNut",
}
APRIORI_MEMBER_OF = {
    "equilibrium": "M0_equilibrium",
    "total_gradient_tble": "M1_pressure_gradient_ode",
}

# ---------------------------------------------------------------------------
# Model identity is not only architecture: it is calibration.  These are the
# constants the coupled runs actually used.
#   * totalGradientTbleNutFvPatchScalarField.C:135-136 hard-codes kappa = 0.41
#     and A+ = 26.0, which are exactly the Python ladder's KAPPA_MIXING and
#     VAN_DRIEST_A -- M1 needs no adjustment.
#   * the cases declare ``type nutUSpaldingWallFunction;`` with no kappa/E
#     entry, so the OpenFOAM Foundation 10 defaults kappa = 0.41, E = 9.8
#     apply, i.e. B = ln(E)/kappa = 5.5668.  The Python ladder's M0 default is
#     B = 5.0.  The primary a-priori M0 here uses the DEPLOYED B; the ladder
#     default is retained as a reported calibration sensitivity so the choice
#     is visible rather than silent.
# ---------------------------------------------------------------------------
KAPPA_DEPLOYED = 0.41
E_DEPLOYED = 9.8
B_DEPLOYED = math.log(E_DEPLOYED) / KAPPA_DEPLOYED
A_PLUS_DEPLOYED = 26.0
B_LADDER_DEFAULT = 5.0
MODELS = HR.MODELS
YM_TAGS = dict(HR.YM_TAGS)
BASELINE_TAG = "0145"
BASELINE_YM = 0.014515746

CAMPAIGN = HR.CAMPAIGN
BASELINE = HR.BASELINE
CURVES_NPZ = ROOT / "codes" / "results" / "r2_3_ym_window_20260824.npz"
SUMMARY_JSON = ROOT / "codes" / "results" / "r2_3_ym_window_20260824_summary.json"
CMH_MAP = ROOT / "codes" / "results" / "critical_matching_height_map.npz"

# (R3) the case under test and its OWN critical-height row
CASE_ROW = "periodic_hills_1p0"
FOREIGN_ROW = "krank_pehill_Re10595"

DENSE_N = HR.DENSE_N
BLOCK = HR.BLOCK
SEED = 20260824


# ---------------------------------------------------------------------------
# case location
# ---------------------------------------------------------------------------
def case_dir(tag: str, grid: str, model: str) -> Path:
    """Directory of the terminal producer attempt backing one sweep point."""
    if tag == BASELINE_TAG:
        g = {"G1c": "g1", "G2c": "g2"}[grid]
        cells = {"G1c": 307200, "G2c": 819200}[grid]
        mtag = "tble" if model == "total_gradient_tble" else "equilibrium"
        return BASELINE / f"rswm_m13_re5600_{g}_{mtag}_{cells}_v2"
    g = {"G1c": "g1", "G2c": "g2"}[grid]
    cells = {"G1c": 307200, "G2c": 819200}[grid]
    mtag = "tble" if model == "total_gradient_tble" else "equilibrium"
    cid = f"rswm_r23m6_ym{tag}_{g}_{mtag}_{cells}_v1"
    key = f"{tag}:{grid}:{model}"
    cont = HR.CONTINUATIONS.get(key)
    if cont is not None:
        # the registered drive-halves continuation supersedes the [135,405]
        # attempt for this one point; harvest_r2_3_ym scores the continuation
        bundle = CAMPAIGN / cont["bundle"] / cont["case_id"]
        manifest = CAMPAIGN / cont["bundle"] / "CAMPAIGN_MANIFEST.json"
        if manifest.is_file() and json.loads(manifest.read_text()).get(
                "status") == "TERMINAL_SIX_CASE_CAMPAIGN_OK":
            return bundle
    return CAMPAIGN / f"ym{tag}" / cid


def deployed_bc(case: Path, patch: str = "bottomWall") -> str:
    """Read the deployed nut boundary-condition type for the wall patch.

    This is the machine-checkable proof of model identity: the paper's claim
    about which wall model ran is taken from the case dictionary, not asserted.
    """
    text = (case / "input" / "nut").read_text(errors="replace")
    m = re.search(rf"^\s*{patch}\s*$\s*\{{\s*type\s+(\w+)\s*;", text, re.MULTILINE)
    if m is None:
        raise SystemExit(f"{case}: cannot read {patch} nut type")
    return m.group(1)


# ---------------------------------------------------------------------------
# (R1) model-matched a-priori branch
# ---------------------------------------------------------------------------
def wall_model_constants(case: Path, model: str) -> dict[str, Any]:
    """Constants the coupled arm deployed, read from the case where declared."""
    text = (case / "input" / "nut").read_text(errors="replace")
    m = re.search(rf"^\s*bottomWall\s*$\s*\{{(.*?)\n    \}}", text, re.MULTILINE | re.DOTALL)
    body = m.group(1) if m else ""
    body = re.sub(r"value\s+nonuniform.*?\n\)\n;", "", body, flags=re.DOTALL)
    def declared(name):
        d = re.search(rf"\b{name}\s+([0-9.eE+-]+)\s*;", body)
        return float(d.group(1)) if d else None
    kappa, E, aplus = declared("kappa"), declared("E"), declared("Aplus")
    if model == "equilibrium":
        return {
            "kappa": kappa if kappa is not None else KAPPA_DEPLOYED,
            "E": E if E is not None else E_DEPLOYED,
            "B": (math.log(E if E is not None else E_DEPLOYED)
                  / (kappa if kappa is not None else KAPPA_DEPLOYED)),
            "declared_in_case": {"kappa": kappa is not None, "E": E is not None},
            "source": ("case dictionary" if (kappa is not None and E is not None)
                       else "OpenFOAM Foundation 10 nutUSpaldingWallFunction defaults "
                            "(the case declares only the BC type)"),
        }
    return {
        "kappa": kappa if kappa is not None else KAPPA_DEPLOYED,
        "A_plus": aplus if aplus is not None else A_PLUS_DEPLOYED,
        "declared_in_case": {"kappa": kappa is not None, "Aplus": aplus is not None},
        "source": ("case dictionary" if (kappa is not None and aplus is not None)
                   else "totalGradientTbleNutFvPatchScalarField.C:135-136 "
                        "(kappa = 0.41, Aplus = 26.0, hard-coded in the deployed kernel)"),
    }


def spalding_at_surface(fields, phase, y_m, kappa: float, b_const: float) -> np.ndarray:
    """M0 exactly as the deployed nutUSpaldingWallFunction defines it."""
    x_targets = np.mod(np.asarray(phase, float), 1.0) * C.LX
    tau = np.empty(len(x_targets))
    for j, (xt, ym) in enumerate(zip(x_targets, np.asarray(y_m, float))):
        i = int(np.argmin(np.abs(fields.x - xt)))
        u_m, _, _ = fields.station(i, ym)
        tau[j] = (C.wm.spalding_wall_stress(u_m, ym, C.NU, kappa=kappa, b_const=b_const)
                  if abs(u_m) > 1e-12 else 0.0)
    return tau


def apriori_at_surface(fields, phase, y_m, member, truth_phase, truth_tau,
                       draws: int, seed: int, b_const: float = B_DEPLOYED,
                       kappa: float = KAPPA_DEPLOYED) -> dict[str, Any]:
    """Evaluate ONE ladder member at the coupled run's own matching surface."""
    if member == "M0_equilibrium":
        tau = spalding_at_surface(fields, phase, y_m, kappa, b_const)
        diag = {"roots_M1": np.full(len(phase), np.nan)}
    else:
        preds, diag = C.ladder_predictions(fields, phase, y_m, models=(member,))
        tau = preds[member]
    if not np.all(np.isfinite(tau)):
        raise SystemExit(f"{member}: non-finite a-priori prediction")
    m, dense, truth_dense, pred_dense = C.phase_metrics(phase, tau, truth_phase, truth_tau)
    samples = C.block_bootstrap_relative_rms(truth_dense, {("a", member): pred_dense},
                                             draws=draws, block=BLOCK, seed=seed)
    return {
        "member": member,
        "relative_rms": m["relative_rms"],
        "r2": m["r2"],
        "relative_rms_interval": C.interval(samples[("a", member)]),
        "sign_accuracy": m["sign_accuracy"],
        "signed_force_ratio": m["signed_force_ratio"],
        "reversed_fraction": m["reversed_fraction"],
        "roots_M1_max": (float(np.nanmax(diag["roots_M1"]))
                         if member == "M1_pressure_gradient_ode" else None),
        "_pred": tau,
    }


# ---------------------------------------------------------------------------
# (R2) commensurate averaging-window sensitivity
# ---------------------------------------------------------------------------
def window_sensitivity(l2, case: Path, truth_phase, truth_tau) -> dict[str, Any]:
    """Score EVERY checkpoint in the same E_tau / R^2 estimand as station+grid."""
    _, _, curves, _ = HM.load_case(l2, case)
    names = list(curves)
    if len(names) < 3:
        raise SystemExit(f"{case}: fewer than three checkpoints")
    t0 = 135.0
    cont = None
    for key, spec in HR.CONTINUATIONS.items():
        if spec["case_id"] == case.name and spec["bundle"] == case.parent.name:
            cont = spec
    if cont is not None:
        t0 = float(cont["drive_t0"])
    per = {}
    for name in names:
        m = l2.metrics(curves[name], truth_phase, truth_tau)
        per[name] = {
            "checkpoint_time": float(name),
            "window_length": float(name) - t0,
            "relative_rms": float(m["relative_rms"]),
            "r2": float(m["r2"]),
        }
    ordered = sorted(per.values(), key=lambda r: r["checkpoint_time"])
    e = [r["relative_rms"] for r in ordered]
    r2 = [r["r2"] for r in ordered]
    return {
        "window_origin": t0,
        "per_checkpoint": per,
        "window_lengths": [r["window_length"] for r in ordered],
        # SAME estimand as station and grid: differences of E_tau (and of R^2)
        "delta_Etau_180_to_225": float(e[1] - e[0]),
        "delta_Etau_225_to_270": float(e[2] - e[1]),
        "max_abs_delta_Etau": float(max(abs(e[1] - e[0]), abs(e[2] - e[1]))),
        "delta_R2_180_to_225": float(r2[1] - r2[0]),
        "delta_R2_225_to_270": float(r2[2] - r2[1]),
        "max_abs_delta_R2": float(max(abs(r2[1] - r2[0]), abs(r2[2] - r2[1]))),
        "estimand": "E_tau = RMS(tau_model - tau_DNS)/RMS(tau_DNS) on the 4096-point dense phase grid",
    }


# ---------------------------------------------------------------------------
# (R4) drive-gate provenance, recorded honestly
# ---------------------------------------------------------------------------
def drive_record(point: dict[str, Any]) -> dict[str, Any]:
    """Report the REGISTERED gate outcome and the exact constraint separately."""
    cb = point.get("crest_bulk", {}) or {}
    dr = point.get("drive_registration", {}) or {}
    st = point.get("drive_stationarity", {}) or {}
    measured = cb.get("crest_bulk_velocity_measured")
    registered = dr.get("crest_bulk_velocity_registered")
    ubar_dev = st.get("window_Ubar_max_abs_deviation")
    dev = (abs(float(measured) - 1.0) if isinstance(measured, (int, float)) else None)
    exact_ok = (
        isinstance(registered, (int, float)) and abs(float(registered) - 1.0) <= 1e-5
        and isinstance(ubar_dev, (int, float)) and float(ubar_dev) <= 1e-4
    )
    return {
        # the check that WAS registered, scored as registered -- no ceiling change
        "registered_single_slice_3pct_gate": {
            "measured_crest_bulk_z2p25": (float(measured) if measured is not None else None),
            "abs_deviation": dev,
            "threshold": 0.03,
            "outcome": (None if dev is None else ("PASS" if dev <= 0.03 else "FAIL")),
        },
        # the constraint that check existed to protect, bound exactly
        "exact_controller_volume_identity": {
            "crest_bulk_velocity_registered": registered,
            "window_Ubar_max_abs_deviation": ubar_dev,
            "registered_volume_average_Ubar": st.get("registered_volume_average_Ubar"),
            "mesh_total_volume": dr.get("mesh_total_volume"),
            "holds": bool(exact_ok),
        },
        # demoted: diagnostic only, no pass/fail authority
        "slice_flux_homogeneity_diagnostic": {
            "max_abs_deviation_fraction": cb.get("slice_flux_max_abs_deviation_fraction"),
            "expected_spanwise_mean": cb.get("slice_flux_expected_spanwise_mean"),
            "authority": "none: ancillary spanwise-homogeneity measurement, not an admission gate",
        },
    }


def spearman(a, b) -> float:
    a, b = np.asarray(a, float), np.asarray(b, float)
    ok = np.isfinite(a) & np.isfinite(b)
    if np.count_nonzero(ok) < 3:
        return math.nan
    ra = np.argsort(np.argsort(a[ok])).astype(float)
    rb = np.argsort(np.argsort(b[ok])).astype(float)
    return float(np.corrcoef(ra, rb)[0, 1])


def permutation_p(a, b, draws: int, seed: int) -> float:
    """Two-sided permutation p for the Spearman statistic (n is small: n<=6)."""
    a, b = np.asarray(a, float), np.asarray(b, float)
    ok = np.isfinite(a) & np.isfinite(b)
    a, b = a[ok], b[ok]
    n = len(a)
    if n < 3:
        return math.nan
    obs = abs(spearman(a, b))
    rng = np.random.default_rng(seed)
    import itertools
    if n <= 8:                                   # exact
        perms = list(itertools.permutations(range(n)))
        hits = sum(1 for p in perms if abs(spearman(a, b[list(p)])) >= obs - 1e-12)
        return float(hits / len(perms))
    hits = sum(1 for _ in range(draws)
               if abs(spearman(a, b[rng.permutation(n)])) >= obs - 1e-12)
    return float((hits + 1) / (draws + 1))


# ---------------------------------------------------------------------------
def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--date", default=_dt.date.today().isoformat().replace("-", ""))
    ap.add_argument("--draws", type=int, default=20000)
    args = ap.parse_args()

    checks: list[tuple[str, bool, str]] = []

    def check(name: str, ok: bool, detail: str = "") -> None:
        checks.append((name, bool(ok), detail))

    l2 = HM.load_module(HM.L2_REDUCER, "rswm_common_surface_grid_l2")
    curves_npz = np.load(CURVES_NPZ, allow_pickle=True)
    deposited = json.loads(SUMMARY_JSON.read_text())
    dep_points = deposited["points"]
    dep_transfer = deposited["transfer_relation"]

    fields = C.DnsTangentFields()
    truth_phase, truth_tau = fields.phase, fields.tau_s_truth

    out: dict[str, Any] = {
        "schema": SCHEMA,
        "date": args.date,
        "node": "development/nodes/node_010",
        "row": "R2-3 / M6 (re-reduction; no new simulation)",
        "case_under_test": "Xiao et al. alpha=1 periodic hill, Re_H = 5600, corrected crest-bulk drive",
        "repairs": {
            "R1_model_identity": "each coupled arm paired with the a-priori evaluation of its own deployed architecture, proved from input/nut",
            "R2_commensurate_sensitivity": "station, grid and averaging-window sensitivities are all differences of E_tau",
            "R3_case_correct_ycrit": f"critical height taken from the {CASE_ROW} row, not {FOREIGN_ROW}",
            "R4_drive_gate_provenance": "registered single-slice 3% gate scored as registered; exact controller/volume identity bound separately; slice fluxes demoted to diagnostic",
        },
        "wall_model_identity": {
            "equilibrium": {
                "deployed_bc": DEPLOYED_BC["equilibrium"],
                "apriori_member": "M0_equilibrium",
                "kappa": KAPPA_DEPLOYED, "E": E_DEPLOYED, "B": B_DEPLOYED,
                "calibration_note": (
                    "the cases declare only 'type nutUSpaldingWallFunction;', so the "
                    "OpenFOAM Foundation 10 defaults kappa = 0.41, E = 9.8 apply and "
                    "B = ln(E)/kappa = 5.5668.  The a-priori M0 is evaluated with THESE "
                    "constants, not the Python ladder's B = 5.0 default; the difference "
                    "is reported per point as spalding_calibration_sensitivity."),
            },
            "total_gradient_tble": {
                "deployed_bc": DEPLOYED_BC["total_gradient_tble"],
                "apriori_member": "M1_pressure_gradient_ode",
                "kappa": KAPPA_DEPLOYED, "A_plus": A_PLUS_DEPLOYED,
                "calibration_note": (
                    "totalGradientTbleNutFvPatchScalarField.C hard-codes kappa = 0.41 and "
                    "Aplus = 26.0; these equal the Python ladder's KAPPA_MIXING and "
                    "VAN_DRIEST_A, so M1 needs no calibration adjustment."),
            },
            "root_selection_note": (
                "M1 keeps the pinned r2m4 root policy (all sign-changing brackets resolved, "
                "the root closest to the Spalding continuation state selected).  That "
                "continuation seed uses the ladder's Spalding default; it is a root-selection "
                "device, not the model, and is left unchanged so this reduction stays "
                "comparable with the closed R2-m4 row.  roots_M1_max is reported per point."),
        },
        "points": {},
        "arrays_note": "per-point a-priori predictions are stored in the npz",
    }
    arrays: dict[str, np.ndarray] = {
        "truth_phase": truth_phase, "truth_tau_s": truth_tau,
    }

    # ---------------- per-point measurement --------------------------------
    order = [(BASELINE_TAG, "G1c"), (BASELINE_TAG, "G2c")] + \
            [(t, "G1c") for t in YM_TAGS] + [(t, "G2c") for t in HR.G2_TAGS]
    ym_of_tag = {BASELINE_TAG: BASELINE_YM, **YM_TAGS}

    for tag, grid in order:
        for model in MODELS:
            key = f"{tag}:{grid}:{model}"
            pref = f"ym{tag}_{grid}_{model}"
            if f"{pref}_phase" not in curves_npz.files:
                dep = dep_points.get(key, {})
                if "model_abort" in dep:
                    out["points"][key] = {
                        "model_abort": dep["model_abort"],
                        "note": ("registered distinct-root abort on ONE trajectory; recorded as an "
                                 "observed deployment failure of the pinned selection policy, not a "
                                 "located operability boundary and not a proof that no wall stress exists"),
                    }
                continue
            case = case_dir(tag, grid, model)
            if not case.is_dir():
                raise SystemExit(f"{key}: case directory absent: {case}")

            # --- (R1) model identity, read from the case ---
            bc = deployed_bc(case)
            member = APRIORI_MEMBER_OF[model]
            check(f"{key}: deployed nut BC is {DEPLOYED_BC[model]}",
                  bc == DEPLOYED_BC[model], f"read {bc}")

            phase = np.asarray(curves_npz[f"{pref}_phase"], float)
            y_m = np.asarray(curves_npz[f"{pref}_ym"], float)
            seed = SEED + int(tag) + (1 if grid == "G2c" else 0) + (7 if model.startswith("total") else 0)

            constants = wall_model_constants(case, model)
            b_dep = constants.get("B", B_DEPLOYED)
            matched = apriori_at_surface(fields, phase, y_m, member, truth_phase,
                                         truth_tau, args.draws, seed,
                                         b_const=b_dep, kappa=constants["kappa"])
            # the OTHER architecture at the SAME surface: quantifies the size of
            # the identity error the deposited reduction made
            other = APRIORI_MEMBER_OF["total_gradient_tble" if model == "equilibrium" else "equilibrium"]
            mismatched = apriori_at_surface(fields, phase, y_m, other, truth_phase,
                                            truth_tau, args.draws, seed,
                                            b_const=B_DEPLOYED, kappa=KAPPA_DEPLOYED)
            # calibration sensitivity: the ladder's own Spalding default B = 5.0
            calib = None
            if member == "M0_equilibrium":
                tau_alt = spalding_at_surface(fields, phase, y_m, constants["kappa"],
                                              B_LADDER_DEFAULT)
                ma, _, _, _ = C.phase_metrics(phase, tau_alt, truth_phase, truth_tau)
                calib = {
                    "B_deployed": b_dep, "B_ladder_default": B_LADDER_DEFAULT,
                    "relative_rms_at_ladder_default_B": ma["relative_rms"],
                    "r2_at_ladder_default_B": ma["r2"],
                    "delta_relative_rms": matched["relative_rms"] - ma["relative_rms"],
                }

            arrays[f"{pref}_apriori_matched_tau"] = matched.pop("_pred")
            arrays[f"{pref}_apriori_mismatched_tau"] = mismatched.pop("_pred")
            arrays[f"{pref}_phase"] = phase
            arrays[f"{pref}_ym"] = y_m

            dep = dep_points[key]
            rec = {
                "case_id": dep.get("case_id"),
                "producer_job_id": dep.get("producer_job_id"),
                "case_dir": str(case.relative_to(ROOT)),
                "ym_over_H": ym_of_tag[tag],
                "ym_measured_flat_over_H": dep["ym_measured_flat_over_H"],
                "ym_plus_dns_median": dep["ym_plus_dns"]["median"],
                "model": model,
                "deployed_nut_bc": bc,
                "apriori_member_matched": member,
                "deployed_constants": constants,
                "spalding_calibration_sensitivity": calib,
                # coupled side: the deposited terminal measurement, unchanged
                "coupled": {
                    "relative_rms": dep["metrics"]["relative_rms"],
                    "r2": dep["metrics"]["r2"],
                    "relative_rms_interval": dep["relative_rms_interval"],
                    "reattachment_x_over_H": dep["metrics"]["reattachment_x_over_H"],
                    "reattachment_bias_over_H": (dep["metrics"]["reattachment_x_over_H"]
                                                 - dep["metrics"]["truth_reattachment_x_over_H"]),
                },
                # a-priori side: model-matched (R1)
                "apriori_matched": matched,
                "apriori_mismatched_architecture": mismatched,
                "apriori_identity_error_factor": (
                    matched["relative_rms"] / mismatched["relative_rms"]
                    if mismatched["relative_rms"] else None),
                # deposited column, retained so the correction is auditable
                "deposited_apriori_relrms_yH_axis": next(
                    (r["apriori_relrms_yH_axis"] for r in dep_transfer
                     if r["ym_tag"] == tag and r["model"] == model), None),
                # (R2)
                "window_sensitivity": window_sensitivity(l2, case, truth_phase, truth_tau),
                # (R4)
                "drive": drive_record(dep),
            }
            out["points"][key] = rec
            print(f"  {key:38s} bc={bc:26s} coupled E_tau={rec['coupled']['relative_rms']:7.3f} "
                  f"apriori({member.split('_')[0]})={matched['relative_rms']:7.3f} "
                  f"[deposited {rec['deposited_apriori_relrms_yH_axis']}]", flush=True)

    # ---------------- (R1) the transfer relation, model-matched -------------
    transfer: dict[str, Any] = {}
    for model in MODELS:
        rows = [(k, v) for k, v in out["points"].items()
                if v.get("model") == model and k.endswith(":G1c:" + model)]
        rows.sort(key=lambda kv: kv[1]["ym_over_H"])
        ymh = [v["ym_over_H"] for _, v in rows]
        cr = [v["coupled"]["relative_rms"] for _, v in rows]
        am = [v["apriori_matched"]["relative_rms"] for _, v in rows]
        ax = [v["apriori_mismatched_architecture"]["relative_rms"] for _, v in rows]
        dep_col = [v["deposited_apriori_relrms_yH_axis"] for _, v in rows]
        rho_m = spearman(cr, am)
        rho_x = spearman(cr, ax)
        # the superseded column is undefined at the largest height (0.25 H lies
        # outside the deposited sweep's y/H range), so its statistic is scored
        # on the heights where it exists -- which is how it was published.
        pair = [(c, d) for c, d in zip(cr, dep_col) if d is not None]
        rho_dep = spearman([c for c, _ in pair], [d for _, d in pair]) if len(pair) >= 3 else math.nan
        transfer[model] = {
            "ym_over_H": ymh,
            "coupled_relative_rms": cr,
            "apriori_matched_relative_rms": am,
            "apriori_matched_r2": [v["apriori_matched"]["r2"] for _, v in rows],
            "apriori_mismatched_relative_rms": ax,
            "deposited_apriori_relative_rms": dep_col,
            "spearman_coupled_vs_apriori_MATCHED": rho_m,
            "spearman_coupled_vs_apriori_MATCHED_permutation_p": permutation_p(cr, am, args.draws, seed=SEED),
            "spearman_coupled_vs_apriori_MISMATCHED": rho_x,
            "spearman_coupled_vs_deposited_column": rho_dep,
            "spearman_coupled_vs_deposited_column_n": len(pair),
            "spearman_coupled_vs_deposited_column_permutation_p": (
                permutation_p([c for c, _ in pair], [d for _, d in pair], args.draws, seed=SEED)
                if len(pair) >= 3 else math.nan),
            "coupled_monotone_in_ym": spearman(cr, ymh),
            "apriori_matched_monotone_in_ym": spearman(am, ymh),
        }
    out["transfer_relation_model_matched"] = transfer

    # the deposited column was model-blind: prove it byte-wise
    dep_eq = [r["apriori_relrms_yH_axis"] for r in dep_transfer if r["model"] == "equilibrium"]
    dep_tb = [r["apriori_relrms_yH_axis"] for r in dep_transfer if r["model"] == "total_gradient_tble"]
    identical = (len(dep_eq) == len(dep_tb)
                 and all((a is None and b is None) or (a is not None and b is not None and a == b)
                         for a, b in zip(dep_eq, dep_tb)))
    out["deposited_column_audit"] = {
        "equilibrium_column": dep_eq,
        "total_gradient_tble_column": dep_tb,
        "byte_identical_across_models": bool(identical),
        "source": "codes/results/epsilon_coupled_predictor.npz sweep_relrms",
        "source_architecture": "ode_wall_model.predict_tau_w (pressure-gradient mixing-length ODE)",
        "consequence": ("the deposited equilibrium transfer statistic compared coupled Spalding "
                        "against a pressure-gradient a-priori model; it is superseded by "
                        "transfer_relation_model_matched"),
    }
    check("deposited a-priori column is byte-identical across the two models (the defect)",
          identical, "confirmed from the deposited summary")

    # ---------------- (R2) the three sensitivities on ONE scale -------------
    sens: dict[str, Any] = {}
    for model in MODELS:
        g1 = {k: v for k, v in out["points"].items()
              if v.get("model") == model and ":G1c:" in k and "model_abort" not in v}
        e = {v["ym_over_H"]: v["coupled"]["relative_rms"] for v in g1.values()}
        station_span = float(max(e.values()) - min(e.values()))
        grid = []
        for tag in HR.G2_TAGS:
            a = out["points"].get(f"{tag}:G1c:{model}")
            b = out["points"].get(f"{tag}:G2c:{model}")
            if a and b and "model_abort" not in b:
                grid.append(abs(b["coupled"]["relative_rms"] - a["coupled"]["relative_rms"]))
        win = [v["window_sensitivity"]["max_abs_delta_Etau"] for v in g1.values()]
        win_r2 = [v["window_sensitivity"]["max_abs_delta_R2"] for v in g1.values()]
        e_r2 = {v["ym_over_H"]: v["coupled"]["r2"] for v in g1.values()}
        grid_r2 = []
        for tag in HR.G2_TAGS:
            a = out["points"].get(f"{tag}:G1c:{model}")
            b = out["points"].get(f"{tag}:G2c:{model}")
            if a and b and "model_abort" not in b:
                grid_r2.append(abs(b["coupled"]["r2"] - a["coupled"]["r2"]))
        sens[model] = {
            "station_span_Etau": station_span,
            "station_span_heights": [min(e), max(e)],
            "max_abs_grid_change_Etau": (max(grid) if grid else None),
            "grid_pairs_scored": len(grid),
            "max_abs_window_change_Etau": float(max(win)),
            "median_abs_window_change_Etau": float(np.median(win)),
            "station_over_window": float(station_span / max(win)) if max(win) > 0 else None,
            "station_over_grid": (float(station_span / max(grid)) if grid and max(grid) > 0 else None),
            # the same three sensitivities in R^2, as an estimand cross-check:
            # a dominance that only exists in one normalisation is not a result
            "station_span_R2": float(max(e_r2.values()) - min(e_r2.values())),
            "max_abs_grid_change_R2": (max(grid_r2) if grid_r2 else None),
            "max_abs_window_change_R2": float(max(win_r2)),
            "station_over_window_R2": (float((max(e_r2.values()) - min(e_r2.values())) / max(win_r2))
                                       if max(win_r2) > 0 else None),
            "station_over_grid_R2": (float((max(e_r2.values()) - min(e_r2.values())) / max(grid_r2))
                                     if grid_r2 and max(grid_r2) > 0 else None),
            "estimand": "all three are differences of E_tau on the same dense phase grid vs the same DNS truth",
            "scope": ("grid ratio uses only completed G1c/G2c pairs; the 2500/G2c TBLE point is a "
                      "registered abort with no score and is excluded, so no grid statement is "
                      "made for total_gradient_tble at the largest height"),
        }
    out["sensitivity_common_scale"] = sens

    # ---------------- grid invariance: EQUALITY OF DECISION SIDES ----------
    # The deposited flag was ``a > 1 and b > 1``.  That is a conjunction, not an
    # invariance test: it reports False for a pair that agrees BELOW one, and it
    # gives a verifier that accepts any non-None Boolean nothing to catch.  The
    # decision the paper makes at a point is the side of E_tau = 1; invariance
    # is therefore (a > 1) == (b > 1), recorded next to both raw values.
    ginv: dict[str, Any] = {}
    for tag in HR.G2_TAGS:
        for model in MODELS:
            a = out["points"].get(f"{tag}:G1c:{model}")
            b = out["points"].get(f"{tag}:G2c:{model}")
            if not a:
                continue
            if not b or "model_abort" in (b or {}):
                ginv[f"{tag}:{model}"] = {
                    "G1c_relative_rms": a["coupled"]["relative_rms"],
                    "G2c_relative_rms": None,
                    "verdict_sides_equal": None,
                    "note": ("the fine-grid run of this pair is a registered distinct-root abort "
                             "with no score; no verdict is fabricated and this pair is excluded "
                             "from every grid statement"),
                }
                continue
            ea, eb = a["coupled"]["relative_rms"], b["coupled"]["relative_rms"]
            ginv[f"{tag}:{model}"] = {
                "G1c_relative_rms": ea,
                "G2c_relative_rms": eb,
                "delta_Etau": float(eb - ea),
                "G1c_side_above_one": bool(ea > 1.0),
                "G2c_side_above_one": bool(eb > 1.0),
                "verdict_sides_equal": bool((ea > 1.0) == (eb > 1.0)),
                "conjunction_a_and_b_above_one": bool(ea > 1.0 and eb > 1.0),
            }
    out["grid_invariance_common_scale"] = ginv
    check("grid invariance is equality of decision sides, not a conjunction",
          all(g["verdict_sides_equal"] == ((g["G1c_relative_rms"] > 1.0) ==
                                           (g["G2c_relative_rms"] > 1.0))
              for g in ginv.values() if g.get("G2c_relative_rms") is not None))

    # ---------------- (R3) case-correct critical matching height -----------
    cmh = np.load(CMH_MAP, allow_pickle=True)
    rows = [str(k) for k in cmh["keys"]]
    i_case, i_foreign = rows.index(CASE_ROW), rows.index(FOREIGN_ROW)
    ymp = np.asarray(cmh["ymp_grid"], float)
    sweep = np.asarray(cmh[f"sweep_relrms__{CASE_ROW}"], float)
    ycrit_case = float(cmh["ycrit"][i_case])
    sampled = sorted(v["ym_plus_dns_median"] for v in out["points"].values()
                     if "ym_plus_dns_median" in v)
    out["critical_matching_height"] = {
        "row_used": CASE_ROW,
        "ycrit_plus": ycrit_case,
        "row_rejected": FOREIGN_ROW,
        "ycrit_plus_rejected": float(cmh["ycrit"][i_foreign]),
        "why": ("the case under test is the Xiao Re_H=5600 periodic hill; its own row is "
                f"{CASE_ROW}.  {FOREIGN_ROW} is a different DNS at Re_H=10595 and its "
                "y_crit+ = 15.93 has no authority over this case."),
        "apriori_relrms_at_grid_floor": float(sweep[0]),
        "grid_floor_yplus": float(ymp[0]),
        "interior_crossing": bool(np.any(sweep < 1.0)),
        "sampled_ym_plus_median_range": [min(sampled), max(sampled)],
        "all_sampled_surfaces_beyond_ycrit": bool(min(sampled) > ycrit_case),
        "statement": ("the a-priori relative error of this case exceeds unity already at the "
                      "lower edge of the swept y+ grid, so y_crit+ = 1.0 is a grid-floor bound, "
                      "not an interior crossing; all sampled coupled surfaces lie beyond it and "
                      "the sweep therefore measures station dependence, not a window crossing"),
    }
    check("critical height uses the case's own row",
          out["critical_matching_height"]["row_used"] == CASE_ROW)
    check("no interior a-priori crossing exists for this case",
          not out["critical_matching_height"]["interior_crossing"],
          f"min relrms over the y+ grid = {float(sweep.min()):.4f}")

    # ---------------- (R4) drive-gate roll-up ------------------------------
    gate = {"registered_3pct_slice_gate": {"PASS": [], "FAIL": []},
            "exact_identity_holds": [], "exact_identity_fails": []}
    for k, v in out["points"].items():
        d = v.get("drive")
        if not d:
            continue
        o = d["registered_single_slice_3pct_gate"]["outcome"]
        if o in gate["registered_3pct_slice_gate"]:
            gate["registered_3pct_slice_gate"][o].append(k)
        (gate["exact_identity_holds"] if d["exact_controller_volume_identity"]["holds"]
         else gate["exact_identity_fails"]).append(k)
    gate["statement"] = (
        f"the registered single-slice 3% admission check FAILED at "
        f"{len(gate['registered_3pct_slice_gate']['FAIL'])} of "
        f"{sum(len(v) for v in gate['registered_3pct_slice_gate'].values())} scored points.  "
        "No replacement ceiling is applied here.  Admission instead rests on the exact "
        "controller/volume identity, which is a stronger and independently checkable "
        "constraint; the single-slice fluxes are reported as a spanwise-homogeneity "
        "diagnostic with no pass/fail authority.")
    out["drive_gate_rollup"] = gate
    check("every scored point satisfies the exact controller/volume identity",
          not gate["exact_identity_fails"], str(gate["exact_identity_fails"]))

    # ---------------- verdicts ---------------------------------------------
    eq, tb = transfer["equilibrium"], transfer["total_gradient_tble"]
    out["verdicts"] = {
        "equilibrium_transfer": {
            "spearman_matched": eq["spearman_coupled_vs_apriori_MATCHED"],
            "permutation_p": eq["spearman_coupled_vs_apriori_MATCHED_permutation_p"],
            "deposited_claim": "anti-transfer rho = -1, p = 0.017 (wrong architecture)",
            "status": ("SUPERSEDED: the deposited value paired coupled Spalding with a "
                       "pressure-gradient a-priori sweep"),
        },
        "tble_transfer": {
            "spearman_matched": tb["spearman_coupled_vs_apriori_MATCHED"],
            "permutation_p": tb["spearman_coupled_vs_apriori_MATCHED_permutation_p"],
        },
    }

    # ---------------- consistency assertions -------------------------------
    for k, v in out["points"].items():
        if "model_abort" in v:
            continue
        check(f"{k}: a-priori member matches the deployed BC",
              APRIORI_MEMBER_OF[v["model"]] == v["apriori_member_matched"])
        cst = v["deployed_constants"]
        check(f"{k}: a-priori calibration equals the deployed calibration",
              abs(cst["kappa"] - KAPPA_DEPLOYED) < 1e-12 and (
                  abs(cst["B"] - B_DEPLOYED) < 1e-9 if v["model"] == "equilibrium"
                  else abs(cst["A_plus"] - A_PLUS_DEPLOYED) < 1e-12),
              json.dumps({k2: cst[k2] for k2 in cst if k2 != "declared_in_case"}))
        ws = v["window_sensitivity"]
        check(f"{k}: window sensitivity is an E_tau difference",
              "E_tau" in ws["estimand"] and len(ws["per_checkpoint"]) == 3)
    for model in MODELS:
        s = sens[model]
        check(f"{model}: station/window ratio uses one estimand",
              s["station_over_window"] is not None and s["max_abs_window_change_Etau"] > 0)

    n_ok = sum(1 for _, ok, _ in checks if ok)
    out["self_checks"] = {"passed": n_ok, "total": len(checks),
                          "detail": [{"name": n, "ok": ok, "note": d} for n, ok, d in checks]}
    out["status"] = "MODEL_MATCHED_TRANSFER_L2_OK" if n_ok == len(checks) else "FAILED"

    stem = ROOT / "codes" / "results" / f"model_matched_transfer_l2_{args.date}"
    arrays["status"] = np.array(out["status"])
    np.savez_compressed(str(stem) + ".npz", **arrays)
    (Path(str(stem) + "_summary.json")).write_text(json.dumps(HM.json_ready(out), indent=2))

    print(f"\nself-checks {n_ok}/{len(checks)}   status={out['status']}")
    for n, ok, d in checks:
        if not ok:
            print(f"  FAIL  {n}  {d}")
    print(f"wrote {stem}.npz and {stem}_summary.json")
    return 0 if out["status"].endswith("OK") else 1


if __name__ == "__main__":
    raise SystemExit(main())
