#!/usr/bin/env python3
"""
sharpness_ladder.py
===================
Harvest + score the EDGE-SHARPNESS ladder (filleted rib, r/k = 0, 0.1, 0.25, 0.5)
generated by codes/openfoam/make_sharpness_ladder_case.py.  Makes "sharpness" a
CONTINUOUS axis bridging the SHARP square rib (r/k=0) and a ROUNDED bump (r/k=0.5).

For each rung:
  * extract wall-normal profiles above the cavity FLOOR (`bottom` patch) -- the
    repeating-structure wall where the 1-D ODE/TBLE wall model is deployed and
    where separation/reattachment between ribs occurs;
  * tau_w (kinematic) = nu * d(u)/dy from the resolved near-wall gradient;
  * dp_dx = d p / d x (p already kinematic, incompressible);
  * matching height fixed at y+~50 (index 10), paper convention;
  * SCORE with the verbatim production instrument cross_geometry_collapse.evaluate
    -> eps_med, R2(tau_w), frac(eps<1), sign accuracy.
Writes ONE row per r/k to codes/results/sharpness_ladder.npz.

Fidelity: OpenFOAM-generated 2D RANS (kOmegaSST). NOT DNS/LES. Never fabricates:
skips a rung (records NaN + reason) if its case did not converge / is missing.
"""
from __future__ import annotations
import os, sys, glob, subprocess
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
CODES = os.path.dirname(HERE)
RESULTS = os.path.join(CODES, "results")
OF = os.path.join(CODES, "openfoam")
sys.path.insert(0, HERE)
from cross_geometry_collapse import evaluate, Y_IDX        # noqa: E402

NU = 1.0 / 4200.0
H = 2.0; DELTA = H / 2.0
K = 0.2; W = 0.2; P = 2.0            # k/delta=0.2, p/k=10
Z_MID = 0.05                          # slab 0..0.1
LINE_LEN = 0.5                        # wall-normal sample length (delta/2)
LINE_NPTS = 200
NPZ_M = 40
VISC_SUB = 0.02                       # near-wall fit window for tau_w
RUNGS = [("0.0", "rk00"), ("0.1", "rk01"), ("0.25", "rk025"), ("0.5", "rk05")]


def of(case, *args):
    env = dict(os.environ, OMP_NUM_THREADS="2")
    return subprocess.run(["simpleFoam", *args], cwd=case, env=env,
                          stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def latest_time(case):
    ts = [d for d in os.listdir(case) if d.replace('.', '').isdigit()
          and os.path.isdir(os.path.join(case, d)) and float(d) > 0]
    return max(ts, key=float) if ts else None


def _ux_tail(case, ntail=200):
    """Median initial Ux residual over the last ntail iters of the latest log.
    The velocity field (hence tau_w = nu dU/dy) is the load-bearing quantity; a
    settled Ux residual certifies tau_w is converged even if p limit-cycles
    slightly above 1e-4 (same honesty guard as harvest_rans_profiles.py)."""
    for lg in ("log.simpleFoam_damp", "log.simpleFoam"):
        p = os.path.join(case, lg)
        if not os.path.exists(p):
            continue
        vals = []
        for ln in open(p, errors="ignore"):
            if "Solving for Ux" in ln and "Initial residual = " in ln:
                try:
                    vals.append(float(ln.split("Initial residual = ")[1].split(",")[0]))
                except Exception:
                    pass
        if vals:
            return float(np.median(vals[-ntail:]))
    return np.inf


def converged(case):
    # accept EITHER an explicit "SIMPLE solution converged" OR a settled Ux
    # residual tail (<1e-4) -> tau_w converged (matches the project honesty guard)
    for lg in ("log.simpleFoam_damp", "log.simpleFoam"):
        p = os.path.join(case, lg)
        if os.path.exists(p) and "SIMPLE solution converged" in open(p, errors="ignore").read():
            return True
    return _ux_tail(case) < 1e-4


def read_boundary_floor(case):
    """Return floor wall-face centres (x,z) and the floor y (=0) for the cavity
    `bottom` patch.  Uses OpenFOAM `postProcess -func writeCellCentres`? Instead we
    sample directly: write a sampling dict over a grid of floor points."""
    # We sample vertical lines on a uniform x-grid across the pitch, on the floor
    # (z = Z_MID), skipping the rib footprint.
    x0, x1 = (P - W) / 2.0, (P + W) / 2.0       # rib base extent (sharp); fillet only on top
    xs = []
    nx = 60
    for i in range(nx):
        x = (i + 0.5) * P / nx
        if x0 - 1e-6 < x < x1 + 1e-6:
            continue                            # inside rib footprint -> no floor column
        xs.append(x)
    return np.array(xs)


def write_floor_lines(case, xs):
    lines = []
    for j, x in enumerate(xs):
        lines.append(
            f"    fl{j:02d}\n    {{\n        type lineUniform;\n        axis distance;\n"
            f"        start ({x:.6e} 1e-5 {Z_MID:.4e});\n"
            f"        end   ({x:.6e} {LINE_LEN:.6e} {Z_MID:.4e});\n"
            f"        nPoints {LINE_NPTS};\n    }}\n")
    block = ("type sets;\nlibs (\"libsampling.so\");\ninterpolationScheme cellPoint;\n"
             "setFormat raw;\nfields (U p);\nwriteControl writeTime;\nsets\n(\n"
             + "".join(lines) + ");\n")
    open(os.path.join(case, "system", "floorLines"), "w").write(block)


def read_line(case, tdir, name):
    d = os.path.join(case, "postProcessing", "floorLines", tdir)
    cand = glob.glob(os.path.join(d, f"{name}.xy"))
    if not cand:
        return None
    arr = np.loadtxt(cand[0])
    if arr.ndim == 1 or arr.shape[0] < Y_IDX + 3:
        return None
    return arr[:, 0], arr[:, 1:4], arr[:, 4]      # dist, U(3), p


def harvest_rung(rk, tag):
    case = os.path.join(OF, f"sharp_ladder_{tag}")
    if not os.path.isdir(case):
        return dict(rk=float(rk), ok=False, reason="case dir missing")
    if not converged(case):
        return dict(rk=float(rk), ok=False, reason="not converged")
    tdir = latest_time(case)
    if tdir is None:
        return dict(rk=float(rk), ok=False, reason="no time dir")
    xs = read_boundary_floor(case)
    write_floor_lines(case, xs)
    of(case, "-postProcess", "-func", "floorLines", "-latestTime")
    ppdir = os.path.join(case, "postProcessing", "floorLines")
    if not os.path.isdir(ppdir):
        return dict(rk=float(rk), ok=False, reason="sampling failed")
    tsub = sorted(os.listdir(ppdir), key=lambda s: float(s) if s.replace('.', '').isdigit() else -1)[-1]

    X, TAU, DPDX = [], [], []
    profs_d, profs_u = [], []
    for j, x in enumerate(xs):
        out = read_line(case, tsub, f"fl{j:02d}")
        if out is None:
            continue
        d, U, p = out
        u = U[:, 0]
        sub = d <= VISC_SUB
        if sub.sum() < 3:
            sub = d <= d[3]
        a = np.sum(u[sub] * d[sub]) / np.sum(d[sub] ** 2)
        X.append(x); TAU.append(NU * a)
        profs_d.append(d); profs_u.append(u); DPDX.append(p[1])   # near-wall p
    if len(X) < 5:
        return dict(rk=float(rk), ok=False, reason=f"only {len(X)} floor columns")
    X = np.array(X); TAU = np.array(TAU)
    order = np.argsort(X)
    X, TAU = X[order], TAU[order]
    pnear = np.array(DPDX)[order]
    dp_dx = np.gradient(pnear, X)
    profs_d = [profs_d[i] for i in order]; profs_u = [profs_u[i] for i in order]

    # matching height y+~50 (station-median), index 10
    u_tau = np.sqrt(np.abs(TAU))
    valid = u_tau > 0
    y_m = float(np.median(50.0 * NU / u_tau[valid]))
    grid = y_m * (np.arange(NPZ_M) / 10.0)
    n = len(X)
    Y = np.tile(grid, (n, 1))
    Umat = np.array([np.interp(grid, profs_d[i], profs_u[i]) for i in range(n)])
    nu_arr = np.full(n, NU)

    prof_path = os.path.join(RESULTS, f"sharpness_ladder_{tag}_wall_profiles.npz")
    np.savez(prof_path, y=Y, U=Umat, tau_w=TAU, dp_dx=dp_dx, x=X, nu=nu_arr, y_m=y_m)
    res = evaluate(prof_path)
    return dict(rk=float(rk), ok=True, reason="",
                n=res["n"], f_sep=res["f_sep"], eps_med=res["eps_med"],
                frac_eps_lt1=res["frac_eps_lt1"], frac_eps_lt0p1=res["frac_eps_lt0p1"],
                relRMS=res["relRMS"], r2=res["r2"], sign_acc_sep=res["sign_acc_sep"],
                y_m=y_m, cells=None)


def main():
    rows = [harvest_rung(rk, tag) for rk, tag in RUNGS]
    rk = np.array([r["rk"] for r in rows])
    ok = np.array([r["ok"] for r in rows])
    def col(k): return np.array([r.get(k, np.nan) for r in rows], float)
    out = os.path.join(RESULTS, "sharpness_ladder.npz")
    np.savez(out,
             rk=rk, ok=ok,
             r2=col("r2"), eps_med=col("eps_med"), frac_eps_lt1=col("frac_eps_lt1"),
             frac_eps_lt0p1=col("frac_eps_lt0p1"), relRMS=col("relRMS"),
             f_sep=col("f_sep"), sign_acc_sep=col("sign_acc_sep"), y_m=col("y_m"),
             k_over_delta=np.full(len(rk), K / DELTA),
             p_over_k=np.full(len(rk), P / K), Re_b=np.full(len(rk), 1.0 * H / NU),
             reason=np.array([r["reason"] for r in rows], dtype=object),
             shape_axis=np.array(["r/k: 0=sharp square rib ... 0.5=rounded bump"], dtype=object),
             fidelity=np.array(["OpenFOAM-generated 2D RANS (kOmegaSST); NOT DNS/LES"], dtype=object))
    print("=" * 72)
    print(f"{'r/k':>5} {'ok':>4} {'n':>4} {'eps_med':>8} {'f(e<1)':>7} {'R2':>9} {'f_sep':>6}  reason")
    for r in rows:
        if r["ok"]:
            print(f"{r['rk']:5.2f} {'Y':>4} {r['n']:4d} {r['eps_med']:8.4f} "
                  f"{r['frac_eps_lt1']:7.3f} {r['r2']:9.4f} {r['f_sep']:6.3f}")
        else:
            print(f"{r['rk']:5.2f} {'N':>4} {'-':>4} {'-':>8} {'-':>7} {'-':>9} {'-':>6}  {r['reason']}")
    print(f"wrote {out}")
    print("=" * 72)


if __name__ == "__main__":
    main()
