#!/usr/bin/env python3
"""Synchronise every registered figure's deposit copies with the rendered master.

The rendered master is always ``manuscript/figures/<stem>.{pdf,png}``.  The flat
submission tree and each registry-declared generator-side twin must be
byte-identical to it, otherwise the paper and the deposit show different
pictures -- the exact defect that let three superseded figures survive a
correction pass.

This is a COPY step only.  It never renders: if a master is older than its
producer or its inputs, the figure must be regenerated by that producer first,
and this script reports the staleness instead of hiding it behind a copy.
"""
from __future__ import annotations

import hashlib
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "codes" / "analysis" / "ledger_verifiers"))
import verify_m23 as M  # noqa: E402


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    copied, stale, missing = [], [], []
    for stem, spec in M.REGISTRY.items():
        master_pdf = M.MAN / "figures" / f"{stem}.pdf"
        if not master_pdf.exists():
            missing.append(stem)
            continue
        script = spec["script"]
        newest_input = max([script] + list(spec["inputs"]),
                           key=lambda p: p.stat().st_mtime if p.exists() else 0)
        if newest_input.exists() and newest_input.stat().st_mtime > master_pdf.stat().st_mtime:
            stale.append(f"{stem}: master older than {newest_input.name}")
            continue
        for suffix in (".pdf", ".png"):
            master = M.MAN / "figures" / f"{stem}{suffix}"
            if not master.exists():
                continue
            destinations = [M.FLAT / f"{stem}{suffix}"]
            destinations += [t for t in spec.get("twins", []) if t.suffix == suffix]
            for dest in destinations:
                if dest.exists() and digest(dest) == digest(master):
                    continue
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(master, dest)
                copied.append(str(dest.relative_to(ROOT)))
    for path in copied:
        print("synced", path)
    for line in stale:
        print("STALE (regenerate its producer, not a copy):", line)
    for stem in missing:
        print("MISSING master:", stem)
    print(f"{len(copied)} copies synchronised, {len(stale)} stale, {len(missing)} missing")
    return 1 if (stale or missing) else 0


if __name__ == "__main__":
    raise SystemExit(main())
